_wandb:
    value:
        cli_version: 0.22.1
        e:
            a6uuzatxb6kb9yeer8if18oizj7uq8ab:
                args:
                    - --cfg_file
                    - tools/cfgs/custom_av/centerpoint_pillar_val.yaml
                    - --num_trials
                    - "10"
                    - --wandb_project
                    - centerpoint-optuna
                    - --gpus
                    - 0,1,2,3
                email: subin.park017@gmail.com
                executable: /usr/bin/python
                git:
                    remote: https://github.com/binxni/team_2.git
                host: b7db4a6adde0
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.29
                program: -m tools.optuna_wandb_tuner
                python: CPython 3.8.10
                root: /workspace/OpenPCDet
                startedAt: "2025-10-03T09:49:02.076040Z"
                writerId: a6uuzatxb6kb9yeer8if18oizj7uq8ab
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 35
            "2":
                - 35
            "3":
                - 2
                - 13
                - 16
            "4": 3.8.10
            "5": 0.22.1
            "10":
                - 20
            "12": 0.22.1
            "13": linux-x86_64
MODEL.DENSE_HEAD.POST_PROCESSING.SCORE_THRESH:
    value: 0.05696756190799966
OPTIMIZATION.DIV_FACTOR:
    value: 13.886218532930638
OPTIMIZATION.LR:
    value: 0.003048919554765756
OPTIMIZATION.PCT_START:
    value: 0.35711721920680584
OPTIMIZATION.WEIGHT_DECAY:
    value: 0.00021839352923182988
